version: '3.8'

services:
  master:
    image: citusdata/citus:11.1
    environment:
      POSTGRES_DB: citus
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data

  worker1:
    image: citusdata/citus:11.1
    environment:
      POSTGRES_DB: citus
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - worker1_data:/var/lib/postgresql/data

  worker2:
    image: citusdata/citus:11.1
    environment:
      POSTGRES_DB: citus
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - worker2_data:/var/lib/postgresql/data

volumes:
  master_data:
  worker1_data:
  worker2_data:
